"""Added class instance without level

Revision ID: 9bc7bc8c31de
Revises: 9d36d5f6a940
Create Date: 2024-01-10 10:49:27.171106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc7bc8c31de'
down_revision: Union[str, None] = '9d36d5f6a940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('level', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
