"""Added Class model

Revision ID: eaefc9d95072
Revises: 99ad26f089c7
Create Date: 2024-01-08 23:54:00.631506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaefc9d95072'
down_revision: Union[str, None] = '99ad26f089c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('teachers_id', sa.Integer(), nullable=True),
    sa.Column('students_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['students_id'], ['students.id'], name=op.f('fk_classes_students_id_students')),
    sa.ForeignKeyConstraint(['teachers_id'], ['teachers.id'], name=op.f('fk_classes_teachers_id_teachers')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classes')
    # ### end Alembic commands ###
